/**
 * useMapMarkers Hook
 *
 * Fetches GeoJSON FeatureCollection pre-generated by the backend.
 * Uses React Query for caching (matches backend 30min cache).
 * Provides O(1) marker lookup via markerMap built from features.
 */

import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { locationsApi } from '../services/locations';

// Empty GeoJSON to avoid null checks
const EMPTY_GEOJSON = { type: 'FeatureCollection', features: [] };

/**
 * Fetch map GeoJSON for all locations
 * @returns {Object} Query result with GeoJSON and lookup map
 */
export function useMapMarkers() {
  const query = useQuery({
    queryKey: ['mapGeoJSON'],
    queryFn: async () => {
      const response = await locationsApi.getMapGeoJSON();
      return response.data;
    },
    staleTime: 30 * 60 * 1000, // 30 minutes (matches backend cache)
  });

  const geojson = query.data || EMPTY_GEOJSON;

  // O(1) lookup map for marker properties by ID
  // Maps feature.properties.id -> feature.properties
  const markerMap = useMemo(() => {
    if (!geojson.features) return new Map();
    return new Map(geojson.features.map((f) => [f.properties.id, f.properties]));
  }, [geojson]);

  // For backwards compatibility, expose markers array
  // (some components may still use markers.length, etc.)
  const markers = useMemo(() => {
    if (!geojson.features) return [];
    return geojson.features.map((f) => ({
      ...f.properties,
      // Coordinates are in properties now, but also keep from geometry for safety
      latitude: f.properties.latitude ?? f.geometry.coordinates[1],
      longitude: f.properties.longitude ?? f.geometry.coordinates[0],
    }));
  }, [geojson]);

  return {
    geojson, // GeoJSON FeatureCollection ready for Mapbox
    markers, // Backwards compatible markers array
    markerMap, // Use markerMap.get(id) for O(1) lookup
    isLoading: query.isLoading,
    isError: query.isError,
    error: query.error,
    refetch: query.refetch,
  };
}

export default useMapMarkers;
