# Generated by Django 5.1.13 on 2025-11-27 18:11

import starview_app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0012_update_all_badge_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_latitude',
            field=models.FloatField(blank=True, help_text="User's location latitude (private - never exposed in API)", null=True, validators=[starview_app.utils.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_longitude',
            field=models.FloatField(blank=True, help_text="User's location longitude (private - never exposed in API)", null=True, validators=[starview_app.utils.validators.validate_longitude]),
        ),
    ]
