# Generated by Django 5.1.13 on 2025-12-25 17:02

import django.db.models.deletion
import starview_app.models.model_location_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0013_add_location_coordinates_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Photo for the location', upload_to=starview_app.models.model_location_photo.location_photo_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail version of the photo', null=True, upload_to=starview_app.models.model_location_photo.location_thumbnail_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='starview_app.location')),
            ],
            options={
                'verbose_name': 'Location Photo',
                'verbose_name_plural': 'Location Photos',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['location', 'order'], name='starview_ap_locatio_62d6e5_idx'), models.Index(fields=['created_at'], name='starview_ap_created_26191c_idx')],
            },
        ),
    ]
