# Generated by Django 5.1.13 on 2025-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0014_add_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('dark_sky_site', 'Dark Sky Site'), ('observatory', 'Observatory'), ('campground', 'Campground'), ('viewpoint', 'Viewpoint'), ('other', 'Other')], default='viewpoint', help_text='Type of stargazing location', max_length=50),
        ),
    ]
