# Generated by Django 5.1.13 on 2025-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0015_add_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific metadata (e.g., phone_number for observatories)'),
        ),
    ]
