# Generated by Django 5.1.13 on 2026-01-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0016_add_type_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unit_preference',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', help_text="User's preferred unit system for distances and elevations", max_length=10),
        ),
    ]
