# Generated by Django 5.1.13 on 2026-01-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0017_add_unit_preference_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_system_account',
            field=models.BooleanField(default=False, help_text='System accounts are hidden from public profiles, sitemaps, and cannot be followed'),
        ),
    ]
