# Generated by Django 5.1.13 on 2026-01-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0018_add_is_system_account_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_prompt_dismissed',
            field=models.BooleanField(default=False, help_text='Whether user has dismissed the location onboarding modal'),
        ),
    ]
