# Generated by Django 5.1.13 on 2026-01-20 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0020_add_mission_ready_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bortle_class',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bortle scale class (1-9, lower is darker)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='location',
            name='bortle_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sky Quality Meter value (mag/arcsec²)', max_digits=4, null=True),
        ),
    ]
