# Generated by Django 5.1.13 on 2026-01-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0024_remove_location_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
