# Generated by Django 5.1.13 on 2026-01-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0025_remove_location_from_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='locationphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
    ]
