# Generated by Django 5.1.13 on 2026-01-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0026_add_dimensions_to_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the location (typically 2-4 sentences about history and stargazing significance)', null=True),
        ),
    ]
