# Generated by Django 5.1.13 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0027_add_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text="User's preferred language for UI and emails", max_length=10),
        ),
    ]
