# Generated by Django 5.1.13 on 2026-01-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0028_add_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('ja', '日本語'), ('de', 'Deutsch'), ('pt-BR', 'Português'), ('zh-CN', '简体中文'), ('ko', '한국어'), ('it', 'Italiano')], default='en', help_text="User's preferred language for UI and emails", max_length=10),
        ),
    ]
