# Generated by Django 5.1.13 on 2026-01-26 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0029_alter_userprofile_language_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_location_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
