# Generated by Django 5.1.13 on 2026-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0030_add_uploaded_by_to_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
    ]
