# Generated by Django 5.1.13 on 2026-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0032_update_photographer_badge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_summary_generated',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last summary generation', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='review_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of user reviews', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='review_summary_stale',
            field=models.BooleanField(default=True, help_text='Whether the review summary needs regeneration'),
        ),
    ]
