# Generated by Django 5.1.13 on 2026-02-02 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0033_location_review_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True if user found the summary helpful, False if not')),
                ('summary_hash', models.CharField(blank=True, default='', help_text='MD5 hash of the summary text when feedback was given', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='The location whose summary was rated', on_delete=django.db.models.deletion.CASCADE, related_name='summary_feedbacks', to='starview_app.location')),
                ('user', models.ForeignKey(help_text='The user who submitted feedback', on_delete=django.db.models.deletion.CASCADE, related_name='summary_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summary Feedback',
                'verbose_name_plural': 'Summary Feedback',
                'indexes': [models.Index(fields=['location', 'is_helpful'], name='starview_ap_locatio_2ef06a_idx')],
                'unique_together': {('user', 'location')},
            },
        ),
    ]
