# Generated by Django 5.1.13 on 2026-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0034_summaryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_feedback_regenerated',
            field=models.DateTimeField(blank=True, help_text='Last time summary was regenerated due to negative feedback', null=True),
        ),
    ]
