# Generated by Django 5.2.17 on 2026-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0037_account_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_queued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
