# Generated by Django 5.2.17 on 2026-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0039_email_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
