# Generated by Django 5.2.17 on 2026-10-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0041_account_mail_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked (Account Lockout)'), ('logout', 'Logout'), ('registration_success', 'Registration Success'), ('registration_failed', 'Registration Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_changed', 'Password Changed'), ('email_change_requested', 'Email Change Requested'), ('email_changed', 'Email Changed'), ('provider_connected', 'Sign-in Provider Connected'), ('provider_disconnected', 'Sign-in Provider Disconnected'), ('mfa_enabled', 'Two-factor Authentication Enabled'), ('mfa_disabled', 'Two-factor Authentication Disabled'), ('mfa_recovery_reset', 'Two-factor Recovery Codes Regenerated'), ('location_verified', 'Location Verified'), ('location_unverified', 'Location Unverified'), ('content_moderated', 'Content Moderated'), ('permission_denied', 'Permission Denied'), ('access_forbidden', 'Access Forbidden')], db_index=True, help_text='Type of security event', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security_version',
            field=models.PositiveIntegerField(db_default=0, default=0, editable=False),
        ),
    ]
