# Generated by Django 5.2.17 on 2026-10-02 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0043_admin_security_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbounce',
            name='sns_message_id',
            field=models.CharField(db_index=True, help_text='AWS SNS message ID; unique with the recipient email', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcomplaint',
            name='sns_message_id',
            field=models.CharField(db_index=True, help_text='AWS SNS message ID; unique with the recipient email', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='emailbounce',
            constraint=models.UniqueConstraint(fields=('sns_message_id', 'email'), name='unique_bounce_recipient_event'),
        ),
        migrations.AddConstraint(
            model_name='emailcomplaint',
            constraint=models.UniqueConstraint(fields=('sns_message_id', 'email'), name='unique_complaint_recipient_event'),
        ),
    ]
