# Generated by Django 5.2.17 on 2026-10-05 18:38

from django.db import migrations, models


def preserve_existing_mfa(apps, schema_editor):
    authenticator = apps.get_model('mfa', 'Authenticator')
    profile = apps.get_model('starview_app', 'UserProfile')
    owners = authenticator.objects.using(schema_editor.connection.alias).filter(
        type__in=('totp', 'webauthn'),
    ).values('user_id')
    profile.objects.using(schema_editor.connection.alias).filter(user_id__in=owners).update(two_factor_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0044_ses_recipient_event_identity'),
        ('mfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(db_default=False, default=False, editable=False),
        ),
        migrations.RunPython(preserve_existing_mfa, migrations.RunPython.noop),
    ]
