# Generated by Django 5.2.17 on 2026-10-06 05:20

from django.db import migrations, models


def preserve_existing_method(apps, schema_editor):
    profile = apps.get_model('starview_app', 'UserProfile')
    authenticator = apps.get_model('mfa', 'Authenticator')
    database = schema_editor.connection.alias
    owners = authenticator.objects.using(database).filter(type='totp').values('user_id')
    profile.objects.using(database).filter(user_id__in=owners).update(two_factor_method='totp')


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0046_mfa_method_events'),
        ('mfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_method',
            field=models.CharField(choices=[('email_code', 'Email code'), ('totp', 'Authenticator app')], db_default='email_code', default='email_code', editable=False, max_length=32),
        ),
        migrations.RunPython(preserve_existing_method, migrations.RunPython.noop),
    ]
