# Generated by Django 5.2.17 on 2026-10-09 17:51

import starview_app.services.birth_dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0048_two_factor_email_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[starview_app.services.birth_dates.validate_birth_date]),
        ),
    ]
