# Generated by Django 5.2.17 on 2026-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starview_app', '0049_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(db_default=False, default=False, help_text='Saved profile privacy preference; visibility enforcement is not yet active'),
        ),
    ]
